### ISSUE TITLE
How should navigation.yml be included

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-resource-template#4]
Blocking #2 

In this template the navigation.yml is a local version, not the latest linked in via `_data`.

This impacts any repository created from this template and also the update action on changes to the template

The result is all new previews will all use the same navigation and NOT the latest? Looking at other repos they mostly link to the latest version of navigation so it seems very odd.

Why would this be the case? As file as I can tell the _data files are only used for the Netlify previews. The published website has it's own `_data` which does link to the latest version of navigation.

I suspect this might have been a temporary thing to test navigation and the link was not restored.

@slhenry  Any thoughts as to why?

**Comment by SteveALee** [comment]
See PR #5 to make it a link

**Comment by slhenry** [comment]
> @slhenry Any thoughts as to why?

No.

I have found many repos where the same thing (e.g., handling multi-page resources) is done in different ways, and I don't find documentation for either way.

I think that's just because Eric changed the way he was doing the thing, and didn't change the old versions (and did leave the old way enabled).

So maybe that is an explanation?

Anyway, please do what you think best &/or if you think important, we can ask...

**Comment by SteveALee** [comment]
Yeah, it's good to make everything consistent when you change.

Anyway I went for the simplest in terms of management by linking to the version in [wai-website-theme](https://github.com/w3c/wai-website-data/blob/master/navigation.yml)

So when the navigation is changed there all newly generated previews will get the changes. Ditto the main site build. So hope that isn't a problem with the potential for new stuff appearing in the site nav before the code is pushed to main. happy to rethink later
